apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: poi
spec:
  replicas: 1 
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1 
  template:
    metadata:
      labels:
        app: poi
    spec:
      containers:
      - name: poi
        image: registryvwj3044.azurecr.io/poi:1.0
        ports:
        - containerPort: 80
        imagePullPolicy: Always  
        env: 
        - name: "SQL_PASSWORD"
          value: "SQL_PASSWORD"
        - name: "SQL_SERVER"
          value: "SQL_SERVER"
        - name: "ASPNETCORE_ENVIRONMENT"
          value: "Production"
