apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: poi
spec:
  replicas: 1 
  template:
    metadata:
      labels:
        app: poi
    spec:
      containers:
      - name: poi
        image: registryvwj3044.azurecr.io/poi:1.0
        ports:
        - containerPort: 80
        imagePullPolicy: Always  
        livenessProbe:
          httpGet:
            path: /api/poi/healthcheck
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /api/poi/healthcheck
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
        env: 
        - name: "SQL_USER"
          valueFrom:
            secretKeyRef:
              name: sqlsecret
              key: sqluser
        - name: "SQL_PASSWORD"
          valueFrom:
            secretKeyRef:
              name: sqlsecret
              key: sqlpassword
        - name: "SQL_SERVER"
          valueFrom:
            secretKeyRef:
              name: sqlsecret
              key: sqlserver
        - name: "SQL_DBNAME"
          valueFrom:
            secretKeyRef:
              name: sqlsecret
              key: sqldbname
        - name: "ASPNETCORE_ENVIRONMENT"
          value: "Production"
