apiVersion: v1
kind: Secret
metadata:
  name: sqlsecret
type: Opaque
data:
  sqluser: sqladminvWj3044
  sqlpassword: iK7160Qx3
  sqlserver: sqlservervwj3044.database.windows.net
  sqldbname: mydrivingDB
