apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: trips
spec:
  replicas: 1 
  template:
    metadata:
      labels:
        app: trips
    spec:
      containers:
      - name: trips
        image: registryvwj3044.azurecr.io/tripinsights/trips:1.0
        ports:
        - containerPort: 80
        imagePullPolicy: Always 
        env: 
        - name: "SQL_PASSWORD"
          valueFrom:
            secretKeyRef:
              name: sqlsecret
              key: sqlpassword
        - name: "SQL_SERVER"
          valueFrom:
            secretKeyRef:
              name: sqlsecret
              key: sqlserver
